// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type SignInInput struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type SignUpInput struct {
	Name     string `json:"Name"`
	Email    string `json:"Email"`
	Password string `json:"Password"`
}
