package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"app/graph/generated"
	"app/graph/model"
	"app/lib/auth"
	models "app/models/generated"
	"app/view"
	"context"
	"fmt"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*models.Todo, error) {
	user := auth.GetUser(ctx)
	if user == nil {
		return &models.Todo{}, view.NewUnauthorizedView(fmt.Errorf("unauthorized error"))
	}

	return r.todoService.CreateTodo(ctx, input, user.ID)
}

// Content is the resolver for the content field.
func (r *todoResolver) Content(ctx context.Context, obj *models.Todo) (string, error) {
	return obj.Content.String, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *todoResolver) CreatedAt(ctx context.Context, obj *models.Todo) (string, error) {
	return obj.CreatedAt.Format("2006-01-02 15:04:05"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *todoResolver) UpdatedAt(ctx context.Context, obj *models.Todo) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02 15:04:05"), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Todo returns generated.TodoResolver implementation.
func (r *Resolver) Todo() generated.TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
